// <auto-generated />
using System;
using MediTrack.MedicalAnalysisService.API.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediTrack.MedicalAnalysisService.API.Migrations
{
    [DbContext(typeof(MedicalAnalysisDbContext))]
    partial class MedicalAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MediTrack.MedicalAnalysisService.API.Domain.Model.Aggregates.AdherenceAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id");

                    b.ToTable("adherence_alert", (string)null);
                });

            modelBuilder.Entity("MediTrack.MedicalAnalysisService.API.Domain.Model.Aggregates.AdherenceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("rate");

                    b.Property<int>("TotalCompliant")
                        .HasColumnType("int")
                        .HasColumnName("total_compliant");

                    b.Property<int>("TotalMissed")
                        .HasColumnType("int")
                        .HasColumnName("total_missed");

                    b.Property<int>("TotalScheduled")
                        .HasColumnType("int")
                        .HasColumnName("total_scheduled");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "Category")
                        .IsUnique();

                    b.ToTable("adherence_metric", (string)null);
                });

            modelBuilder.Entity("MediTrack.MedicalAnalysisService.API.Domain.Model.Aggregates.ClinicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("ImportBatchId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("record_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("clinical_record", (string)null);
                });

            modelBuilder.Entity("MediTrack.MedicalAnalysisService.API.Domain.Model.Aggregates.ComplianceStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("calculated_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<decimal>("ComplianceRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("compliance_rate");

                    b.Property<int>("TotalCompliant")
                        .HasColumnType("int")
                        .HasColumnName("total_compliant");

                    b.Property<int>("TotalMissed")
                        .HasColumnType("int")
                        .HasColumnName("total_missed");

                    b.Property<int>("TotalScheduled")
                        .HasColumnType("int")
                        .HasColumnName("total_scheduled");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.ToTable("compliance_statistic", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
